pipeline {
    agent any
    tools {
      nodejs 'node1'
    }
    stages { 
         stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/Ayus1123/youtube-content.git'
            }
        }
        stage('print versions') {
          steps {
            sh 'npm version'
          }
        }
        stage('Install') { 
            steps {
              sh 'npm install'
            }
        }
        stage('Build') { 
            steps {
                sh 'npm run build' 
            }
        }
        stage('codedeploy'){
          steps {
            step([$class: 'AWSCodeDeployPublisher', applicationName: 'node-application', deploymentGroupAppspec: false, deploymentGroupName: 'nodeJs-DG', excludes: '', iamRoleArn: '', includes: 'dist/', proxyHost: '', proxyPort: 0, region: 'ap-southeast-1', s3bucket: 'jenkins1-bucket1', s3prefix: '', subdirectory: '', versionFileName: '', waitForCompletion: false])
           }
        }
        }
    }
}
